import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Layout from "@/layout";

const beVietnam = Be_Vietnam_Pro({
  weight: ["300", "600", "800"],
  subsets: ["latin"],
  variable: "--font-be_vietnam",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnam.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
